#! /bin/sh
# pppdfcode - create PDFs for the all-text source files under cwd
# copyright 2013 Ed Cashin <ecashin@noserose.net>
# released under GPLv2 license
#
# options (that must come before other stuff on CLI):
#   -n N	put N files in each generated PDF (default 10)
#   -L M	start next output file after M lines
#               [incompatible with -n; output can have >M lines]
#   -p foo	require password "foo" to open resulting PDF
#   -r		resume, do not generate intermediate PS files
#   -N NAME	output will be ~/tmp/pppdfcode-NAME/NAME-i.pdf

dieusage() {
	exec 1>&2
	echo usage: `basename "$0"` "[-r] [-n N|-L m] [-p passwd] [-N name]"
	exit 1
}

p=
n=10
resume=
name=`pwd`
name=`basename "$name"`
while true; do
	case "$1" in
	-n)
		shift
		test "$1" || dieusage
		expr "$1" + 3 > /dev/null 2>&1 || dieusage
		n="$1"
		shift
		;;
	-L)
		shift
		test "$1" || dieusage
		L="$1"
		shift
		;;
	-p)
		shift
		test "$1" || dieusage
		p="$1"
		shift
		;;
	-r)
		resume=yes
		shift
		;;
	-N)
		shift
		test "$1" || dieusage
		name="$1"
		shift
		;;
	'-?')
		dieusage
		;;
	*)
		break
		;;
	esac
done

set -e

o=$HOME/tmp/`basename $0`-"$name"

if test "$resume" != "yes"; then
	rm -rf "$o"/*
	
	find . ! -type d | while read f; do
		b=`basename "$f"`
		d="$o/"`dirname "$f"`
		mkdir -p "$d"
		enscript -f Courier12 -G --color=1 --line-numbers -o "$d"/"$b".ps "$f"
	done
fi

cd "$o"

i=0
brk=
find . -name '*.ps' -type f | while true; do
	i=`expr "$i" + 1`
	files=
	j=0
	k=0
	while true; do
		if test "$L"; then
			if test "$k" -ge "$L"; then
				break
			fi
		else
			if test "$j" -ge "$n"; then
				break
			fi
		fi
		read f || true
		test "$f" || { brk=yes; break; }
		files="$files $f"
		j=`expr "$j" + 1`
		lines=`wc -l < "$f"`
		k=`expr $k + $lines`
	done
	if test "$files"; then
		if test "$p"; then
			gs -q -dNOPAUSE -dBATCH -sDEVICE=pdfwrite \
				-sUserPassword="$p" -sOwnerPassword="$p" \
				-sOutputFile="$name"-"$i".pdf $files
		else
			gs -q -dNOPAUSE -dBATCH -sDEVICE=pdfwrite \
				-sOutputFile="$name"-"$i".pdf $files
		fi
	fi
	if test "$brk" = "yes"; then
		break
	fi
	printf "%d" `expr "$i" '*' "$n"`
	if test "$i" -gt 0 && test `expr "$i" % 20` = "0"; then
		echo
	else
		printf "%s" " "
	fi
done

	
